  jco.client.ashost: rogerionascimento.com
  jco.client.sysnr: '0'
  jco.client.client: '100'
  jco.client.lang: EN
  jco.client.user: rogerio
  jco.client.passwd: wolvie
  jco.destination.peak_limit: 30
  jco.destination.pool_capacity: 15
  jco.destination.expiration_time: 60000
  jco.destination.expiration_check_period: 30000
  jco.destination.max_get_client_time: 5000